#!/usr/bin/make
#
# Makefile for tmux assistance.
#
# Created on: 04.11.16

include ../utils/pre-var.mk

### Variables ###
_TMUX_CONF_FILE :=$(HOME)/.tmux.conf
PACKAGES        += tmux xclip

include ../utils/post-var.mk
